"""Vehicle Observation catalog profile."""

from __future__ import annotations

from horizon_catalog.models import ObservationDefinition, ValueType
from horizon_catalog.registry import ObservationCatalogRegistry


def create_vehicle_catalog() -> ObservationCatalogRegistry:
    """Create the official Vehicle Observation catalog."""
    return ObservationCatalogRegistry(vehicle_definitions())


def vehicle_definitions() -> tuple[ObservationDefinition, ...]:
    """Return internal Vehicle Observation definitions."""
    return (
        ObservationDefinition(
            id="engine.rpm",
            label="RPM do motor",
            category="Motor",
            unit="rpm",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Rotação atual do motor.",
            aliases=("rpm", "engine_rpm"),
            display_order=10,
        ),
        ObservationDefinition(
            id="engine.temperature",
            label="Temperatura do motor",
            category="Motor",
            unit="celsius",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Temperatura operacional do motor.",
            aliases=("temperature", "engine_temperature"),
            display_order=20,
        ),
        ObservationDefinition(
            id="engine.oil_pressure",
            label="Pressão do óleo",
            category="Motor",
            unit="bar",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Pressão do óleo do motor.",
            aliases=("pressure", "oil_pressure"),
            display_order=30,
        ),
        ObservationDefinition(
            id="electrical.battery_voltage",
            label="Tensão da bateria",
            category="Elétrica",
            unit="volt",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Tensão medida na bateria.",
            aliases=("voltage", "battery_voltage"),
            display_order=40,
        ),
        ObservationDefinition(
            id="electrical.alternator_voltage",
            label="Tensão do alternador",
            category="Elétrica",
            unit="volt",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Tensão medida no alternador.",
            aliases=("voltage", "alternator_voltage"),
            display_order=50,
        ),
        ObservationDefinition(
            id="fuel.type",
            label="Tipo de combustível",
            category="Combustível",
            unit="type",
            value_type=ValueType.ENUM,
            default_source="manual",
            description="Tipo de combustível usado pelo Asset.",
            aliases=("fuel_type",),
            enum_values=("gasoline", "ethanol", "diesel", "electric", "hybrid"),
            display_order=60,
        ),
        ObservationDefinition(
            id="fuel.level",
            label="Nível de combustível",
            category="Combustível",
            unit="percent",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Percentual estimado de combustível.",
            aliases=("fuel_level",),
            display_order=70,
        ),
        ObservationDefinition(
            id="fuel.consumption",
            label="Consumo",
            category="Combustível",
            unit="km/l",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Consumo médio observado.",
            aliases=("generic", "fuel_consumption"),
            display_order=80,
        ),
        ObservationDefinition(
            id="transmission.gear",
            label="Marcha",
            category="Transmissão",
            unit="gear",
            value_type=ValueType.ENUM,
            default_source="manual",
            description="Marcha atual da transmissão.",
            aliases=("gear",),
            enum_values=("P", "R", "N", "D", "1", "2", "3", "4", "5", "6"),
            display_order=90,
        ),
        ObservationDefinition(
            id="motion.speed",
            label="Velocidade",
            category="Movimento",
            unit="km/h",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Velocidade observada.",
            aliases=("speed",),
            display_order=100,
        ),
        ObservationDefinition(
            id="motion.odometer",
            label="Odômetro",
            category="Movimento",
            unit="km",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Quilometragem acumulada.",
            aliases=("distance", "odometer"),
            display_order=110,
        ),
        ObservationDefinition(
            id="location.latitude",
            label="Latitude",
            category="Localização",
            unit="degrees",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Latitude observada.",
            aliases=("location", "latitude"),
            display_order=120,
        ),
        ObservationDefinition(
            id="location.longitude",
            label="Longitude",
            category="Localização",
            unit="degrees",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Longitude observada.",
            aliases=("location", "longitude"),
            display_order=130,
        ),
        ObservationDefinition(
            id="location.altitude",
            label="Altitude",
            category="Localização",
            unit="m",
            value_type=ValueType.NUMBER,
            default_source="manual",
            description="Altitude observada.",
            aliases=("location", "altitude"),
            display_order=140,
        ),
    )
